# Generated by Django 3.0.1 on 2020-01-21 01:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200120_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(default='', verbose_name=django.contrib.auth.models.User),
            preserve_default=True,
        ),
    ]
